
server:
  port: 8083
  servlet:
    session:
      cookie:
        name: CLIENT_A_SESSION

security:
  oauth2:
    client:
      client-id: c1
      client-secret: secret
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      jwt:
        key-uri: http://localhost:8080/oauth/token_key
      user-info-uri: http://localhost:8080/userInfo # 从授权服务器获取当前登录用户信息的地址

spring:
  thymeleaf:
    cache: false
